name: Australian Equity Price Scan

on:
  schedule:
    # At 11:00 AM and 2:00 PM AEST (00:00 and 03:00 UTC)
    - cron: '0 0,3 * * 1-5'
  workflow_dispatch: # Allow manual trigger

jobs:
  ticker-intersection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Make scripts executable
      run: |
        chmod +x aus-ep-scan/tv_scan.sh
        chmod +x aus-ep-scan/asx_ann_scan.sh
        chmod +x aus-ep-scan/find_intersection.sh
    
    - name: Run TradingView momentum scan
      run: ./aus-ep-scan/tv_scan.sh momentum_tickers_raw.json
        
    - name: Run ASX price sensitive scan
      run: ./aus-ep-scan/asx_ann_scan.sh sensitive_tickers.json
        
    - name: Find intersection and trigger alert
      run: ./aus-ep-scan/find_intersection.sh momentum_tickers_raw.json sensitive_tickers.json